version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:11.0.13
        environment:
          MAVEN_OPTS: -Xmx1g
  build-debian-executor:
    docker:
      - image: cimg/openjdk:11.0
        environment:
          MAVEN_OPTS: -Xmx2g

orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.5
  sign-packages: opennms/sign-packages@2.3.0
  #github-cli: circleci/github-cli@2.2.0

workflows:
  build-deploy:
    jobs:
      - build:
          context:
            - gpg-signing
          filters:
            tags:
              only:
                - /^v.*/
      - tests:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
      - build-debian:
          context: "OpenNMS Build"
          requires:
            - build
            - tests
          #filters:
          #  tags:
          #    only:
          #      - /release-.*/
          #  branches:
          #    only:
          #      - main
          #      - /release-.*/
          #      - /.*-package/

      - prepare-release:
          requires:
            - tests
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      #- github-cli/release:
      #    context:
      #      - github-releases      
      #    token: GH_TOKEN
      #    tag: $CIRCLE_TAG
      #    title: The $CIRCLE_TAG release
      #    files: ~/output/.*
      #    prerelease: true
      #    #notes: changelog.md
      #    requires:
      #      - prepare-release
      #    filters:
      #      tags:
      #        only:
      #          - /^v.*/
      #      branches:
      #        ignore: /.*/
      - publish-github-release:
          context: 
            - github-releases
          requires:
            - prepare-release
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/     
      #- deploy-packages:
      #    context: 
      #      - gpg-signing
      #      - cloudsmith-publish-account
      #    requires:
      #      - tests
      #      - build-debian
      #    filters:
      #      tags:
      #        only:
      #          - /^v.*/
      #      branches:
      #        only:
      #          - main
      #          - /release-.*/


jobs:
  build:
    executor: build-executor
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Compile source without tests
          command: |
            mvn -DskipITs=true -DskipTests=true clean install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - .m2
            - project
      #- store_artifacts:
      #    path: ~/kar
      #    destination: artifact-file

  tests:
    executor: build-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run integration tests
          command: |
            mvn -DskipITs=false -DskipTests=false clean install test 
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

  deploy:
    executor: build-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - sign-packages/setup-env:
          skip_if_forked_pr: true
      - run:
          name: Deploy to Maven
          command: |
            mvn -Prelease -s .circleci/.circleci.settings.xml -Ddisable.checkstyle=true -DskipTests -Dmaven.verify.skip=true -Dmaven.install.skip=true deploy

  deploy-packages:
    executor: cloudsmith/default
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/

      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli

      - run:
          name: Push packages to CloudSmith
          command: .circleci/scripts/publish-cloudsmith.sh

  prepare-release:
    executor: build-executor
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Gather artifacts
          command: |
              mkdir ~/output
              # We need a better logic here
              find ~/project -type f -regex ".*.jar" -exec cp {} ~/output \;
              find ~/project -type f -regex ".*.rpm" -exec cp {} ~/output \;
              find ~/project -type f -regex ".*.deb" -exec cp {} ~/output \;
              find ~/project -type f -regex ".*.kar" -exec cp {} ~/output \;
      - persist_to_workspace:
          root: ~/
          paths:
            - output
  publish-github-release:
    executor: build-executor
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install GitHub CLI and Publish release on GitHub
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then 
              echo "Skipping step as we don't have a tag!"
            else 
              tag=${CIRCLE_TAG}

              # Install GitHub CLI
              type -p curl >/dev/null || sudo apt install curl -y
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
              && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
              && sudo apt update \
              && sudo apt install gh -y
              
              gh release create $tag --title "$tag Release" --notes "$tag prerelease!" --prerelease --generate-notes 

              gh release upload $tag ~/output/*.jar
            fi


  build-debian:
    executor: build-debian-executor

    steps:
      - attach_workspace:
          at: ~/

      - sign-packages/install-deb-dependencies:
          skip_if_forked_pr: true
          use_sudo: true
      - sign-packages/setup-env:
          skip_if_forked_pr: true

      - restore_cache:
          keys:
            # Use a separate cache, since the the other build image runs as root
            - v4-deb-dependencies-{{ checksum "pom.xml" }}
            - v4-deb-dependencies-

      - run:
          name: Install fakeroot
          command: sudo apt install -y fakeroot 

      - run:
          name: Build Debian packages
          command: |
            # avoid release-[0-9].x go into release
            if [[ ! << pipeline.git.branch >> =~ ^release-[0-9.]*$ ]]; then
              MVN_OPTIONS="-Psnapshot"
            else
              MVN_OPTIONS="-Prelease"
              BUILD_NUMBER=$(echo '<< pipeline.git.branch >>' | sed -e 's/release-[^-]*-*//')
              if [[ -z "$BUILD_NUMBER" ]]; then
                BUILD_NUMBER=1
              fi
              MVN_OPTIONS="${MVN_OPTIONS} -DbuildNumber=${BUILD_NUMBER}"
            fi
            mvn install ${MVN_OPTIONS} --projects org.opennms.plugins.TEMPLATE.assembly:org.opennms.plugins.TEMPLATE.assembly.opennms.deb,org.opennms.plugins.TEMPLATE.assembly:org.opennms.plugins.TEMPLATE.assembly.sentinel.deb --also-make -DskipTests=true -Dbuild.packages

      - run:
          name: Remove old artifacts to keep workspace size down
          command: .circleci/scripts/clean-dir.sh "$HOME/.m2/repository"

      - save_cache:
          paths:
            - ~/.m2
          key: v4-deb-dependencies-{{ checksum "pom.xml" }}

      - sign-packages/sign-debs:
          skip_if_forked_pr: true
          gnupg_key: opennms@opennms.org
          packages: assembly/*-deb/target/*.deb

      - run:
          name: Gather artifacts
          command: |
            mkdir -p ~/dist/
            cp assembly/opennms-deb/target/opennms-plugin-TEMPLATE_*.deb ~/dist/
            cp assembly/sentinel-deb/target/sentinel-plugin-TEMPLATE_*.deb ~/dist/

      - store_artifacts:
          path: ~/dist
          destination: dist

      - persist_to_workspace:
          root: ~/
          paths:
            - project/assembly/



